version: '3'

services:
  db:
    image: mariadb
    # image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  app:  
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - db.env

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db:
  nextcloud:
